### ISSUE TITLE
NCGR-Q需求4级海盗插 

### ISSUE THREAD

**Issue by Greeed-islanl** [Greeed-islanl/frat-work-log-or-calendar#28]
NCGR-Q需求4级海盗插 
意见反馈 Feedback
IHub 插需求

从我们上一次看到 SinonJZH 有一阵子了 — 他上次发帖是 5 个月前.

SinonJZH
诗乃
1 天
星系(System)：NCGR-Q
军等(Mil. Index)：4 级 + 10%

**Comment by Greeed-islanl** [comment]
@TheDoctorW

**Comment by TheDoctorW** [comment]
FUXI的IHUB，所有海盗插都在牛蛙那，去联系他

**Comment by Greeed-islanl** [comment]
OK
